
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Moklet
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tinggi = new javax.swing.JTextField();
        Panjang = new javax.swing.JTextField();
        Lebar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Sisi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jr = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROGRAM PENGHITUNG VOLUME BANGUN RUANG");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 10, 290, 14);

        jPanel1.setLayout(null);

        jLabel2.setText("Masukkan Tinggi");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 120, 120, 14);

        jLabel3.setText("Masukkan Panjang");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 20, 120, 14);

        jLabel4.setText("Masukkan Lebar");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 70, 120, 14);
        jPanel1.add(Tinggi);
        Tinggi.setBounds(150, 110, 90, 30);
        jPanel1.add(Panjang);
        Panjang.setBounds(150, 10, 90, 30);
        jPanel1.add(Lebar);
        Lebar.setBounds(150, 60, 90, 30);

        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 120, 34, 14);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 20, 30, 14);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(250, 70, 34, 14);

        jButton1.setText("HITUNG VOLUME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 150, 150, 30);

        jTabbedPane1.addTab("BALOK", jPanel1);

        jPanel3.setLayout(null);

        jLabel10.setText("Masukkan Panjang Sisi");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 20, 130, 14);
        jPanel3.add(Sisi);
        Sisi.setBounds(150, 10, 80, 30);

        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(240, 20, 50, 14);

        jButton3.setText("HITUNG VOLUME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(10, 60, 150, 23);

        jTabbedPane1.addTab("KUBUS", jPanel3);

        jPanel2.setLayout(null);

        jLabel8.setText("Masukkan Panjang Jari-jari");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 20, 170, 14);
        jPanel2.add(jr);
        jr.setBounds(180, 10, 80, 30);

        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(270, 20, 40, 14);

        jButton2.setText("HITUNG VOLUME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(10, 60, 150, 23);

        jTabbedPane1.addTab("BOLA", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 30, 400, 270);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(Panjang.getText());
        lebar = Integer.parseInt(Lebar.getText());
        tinggi = Integer.parseInt(Tinggi.getText());
        
        int hasil = panjang * lebar * tinggi;
        
        try {
            JOptionPane.showMessageDialog(null, "Volume Balok adalah : " +hasil,
                    "luas", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: "+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int sisi;
        sisi = Integer.parseInt(Sisi.getText());
        int hasil = sisi*sisi*sisi;
        
        try {
            JOptionPane.showMessageDialog(null, "Volume Kubus adalah : " +hasil,
                    "luas", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: "+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int jari;
        jari = Integer.parseInt(jr.getText());
        float hasil = (float) (4/3 * 3.14 * jari*jari*jari);
        
        try {
            JOptionPane.showMessageDialog(null, "Volume Bola adalah : " +hasil,
                    "luas", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: "+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Lebar;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField Sisi;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jr;
    // End of variables declaration//GEN-END:variables
}
